const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const generateRandomString = (length = 64) => {
  return crypto.randomBytes(length).toString("hex").slice(0, length);
};

const generateEnvContent = () => {
  const dbPassword = generateRandomString(32);
  const masterEncryptionKey = generateRandomString(64);
  const livenessSecret = generateRandomString(48);

  return `# Generated on ${new Date().toISOString()}
# This file was auto-generated by generate-env.js
# Do not commit this file to version control

# Database
DB_PASSWORD=${dbPassword}

# Security
MASTER_ENCRYPTION_KEY=${masterEncryptionKey}
LIVENESS_SECRET=${livenessSecret}
`;
};

const writeEnvFile = () => {
  const envPath = path.join(__dirname, "..", ".env");

  if (fs.existsSync(envPath)) {
    console.log("Warning: .env file already exists. Skipping generation.");
    return;
  }

  try {
    fs.writeFileSync(envPath, generateEnvContent(), "utf8");
    console.log(`Successfully generated .env file at: ${envPath}`);
  } catch (error) {
    console.error("Error writing .env file:", error.message);
    process.exit(1);
  }
};

writeEnvFile();